version: '3.8'
services:
  bookings-postgres-db:
    container_name: bookings-postgres-db
    image: postgres:15.5-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - bookings-postgres-db:/var/lib/postgresql/data

volumes:
  bookings-postgres-db:
